### ISSUE TITLE
Syntax Error on registryVocab.ttl

### ISSUE THREAD

**Issue by shaneseaton** [UKGovLD/registry-core#118]
You are missing a '.' at the end of a set of statements. My tools are unable to parse the ttl. 

https://github.com/UKGovLD/registry-core/blob/master/src/main/vocabs/registryVocab.ttl

Line 213.

**Comment by der** [comment]
Thanks, fixing it now.

@simonoakesepimorphics Looks like came it as part of https://github.com/UKGovLD/registry-core/pull/111
