### ISSUE TITLE
CSV Roundtrip failure when text values contain apostrophies.

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#142]
Round-tripping CSV's from the registry fails when text (xsd:string or rdf:langString) values contain apostrophes (`'`) characters. On export, for example, "King's Lynn Port Health Authority" is rendered in a CSV file as 

`'King's Lynn Port Health Authority'@en` 

On re-importing into the registry, the aposthophe  before the `s` is interpreted as matching the opening single quote string delimiter. As the text field is used literally as in the internal construction of a turtle fragment, the string needs to be rendered as:

`'''King's Lynn Port Health Authority'''@en`

Using there single quotes to act a (turtle) sting delimiters. A single or triple double quote might also work, but double quotes are also used as quoting characters within CSV files, typically  to 'protect' comma in text values being interpreted as field delimiters.

This of course leaves the unlikely problem of a text value that embeds 3 consecutive single quotes e.g.

`'''abc'''def'''@en`

An alternate strategy that might work would be to `\` escape the single quote characters within the text value e.g.

`'King\'s Lynn Port Health Authority'@en`

**Comment by skwlilac** [comment]
Just tried it out `\'` escaping of the inner `'` does work. Obviously need to also `\` escape any `\` in the present in the running text as well.

**Comment by ajtucker** [comment]
We saw this again yesterday with the same `'King's Lynn...` cell value being output. Luckily @skwlilac remembered that he'd seen the issue already as well as the fix :)

Looking at the code, while plain literals appear to have any `'` characters escaped, this isn't the case for lang or datatype literals. See https://github.com/UKGovLD/registry-core/blob/master/src/main/java/com/epimorphics/registry/csv/RDFCSVUtil.java#L92 for the case of lang literals.
