### ISSUE TITLE
Minimum/Recommended System Requirements

### ISSUE THREAD

**Issue by mike-gormley** [UKGovLD/registry-core#155]
Hello,

New here to the registry. I can't seem to find it in the wiki any where but could anyone inform me of what the minimum/recommended system requirements are for running the latest version of the registry (v2.3.7 at time of writing)? e.g. versions of OS, java, tomcat etc.

Many thanks,
Mike

**Comment by der** [comment]
Hi Mike,

Minimum requirements are java-8 and tomcat-7. It's compatible with tomcat-8 and should also be compatible with java-11 (and probably later but not tested).

I'd recommend java-8 and tomcat-8 as a good default.

While it should be compatible with windows we run on linux distributions and would recommend sticking to that. 

Memory and disk sizes will depend on the volume of data but generally modest.

Dave

**Comment by mike-gormley** [comment]
Hi Dave, thanks for the prompt reply. It might be a good suggestion to include that information somewhere in the wiki.

I got there in the end (I think!). I don't know how much you know about Amazon AWS but I was initially using the latest Amazon Linux 2 image for an EC2 to get started and that includes JDK 17 and Tomcat 7 (weird combination). I was getting Java errors, so specifically configured Java 8 instead and that removed some of the Java errors.
I was able to run registry-core 2.3.3 but upgrading higher than 2.3.4 threw errors around Shiro in the Tomcat logs, so it seems Tomcat 7 doesn't appear to be compatible with the current Apache Shiro 1.8.0 used (I think you were using something like Shiro 1.4 before). 

In between my initial message here and your reply I attempted to go with Tomcat 9 and that now seems to be working. Once I finish a few more other tasks, I might revisit to see if I can bump up to JDK 11 (or 17 again) now the Tomcat issue is resolved but at least it is working for me now.

**Comment by der** [comment]
Interesting. We are running 2.3.6 on jdk8/tomcat-7 combination in at least one place so that Shiro/tomcat combination isn't always fatal.

We tend to run in docker images and use the Amazon Corretto jdk8 base image.

Glad you got it working.

Can we close this as an issue?

For general discussion there is a Google group that your colleague Mark set up https://groups.google.com/g/ukgovld-software. It's been very quiet of late but should still be usable.

**Comment by mike-gormley** [comment]
Yes happy to close, just for info the errors I was receiving in Tomcat localhost.2022-01-13.log after using JDK 8/Tomcat 7.0.76 were:

> Jan 13, 2022 3:21:47 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class com.epimorphics.appbase.core.AppConfig
java.lang.LinkageError: loader constraint violation: loader (instance of java/net/URLClassLoader) previously initiated loading for a different type with name "org/apache/log4j/Layout"

and 

> Jan 13, 2022 3:21:47 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.apache.shiro.web.env.EnvironmentLoaderListener
org.apache.shiro.config.ConfigurationException: Unable to set property 'userStoreFromRegistry' with value [true] on object of type com.epimorphics.registry.security.RegRealm.  If 'true' is a reference to another (previously defined) object, prefix it with '$' to indicate that thereferenced object should be used as the actual value.  For example, $true
