### ISSUE TITLE
logging configuration

### ISSUE THREAD

**Issue by tendrie** [UKGovLD/registry-core#157]
Hi,  
I would like to ask how and where we can configure log levels for ldregistry. 
We want to set to DEBUG but cannot find the file (log4J properties?) We tried to configure the one in Tomcat, it doesn't seem to work.
Thank you

**Comment by der** [comment]
Hi,
With the change to use log4j2 the logging configuration is now in `src/main/resources/log4j2.xml`
For debug purposes you should be able to unpack the war file and then repack that with a changed config rather than have to do a full source rebuild.

**Comment by tendrie** [comment]
Thank you for your answer.  It's working now
