### ISSUE TITLE
XSS patch regression on Return button 

### ISSUE THREAD

**Issue by tendrie** [UKGovLD/registry-core#193]
Hello,
Related to https://github.com/UKGovLD/registry-core/issues/185
We have deployed the latestest version of registry core , and  config base. We still have issue on return button. To reproduce, we just need to click on a return button:

1. Open [login  ](https://terra-vocabulary.org/ncl/ui/login?return=http://terra-vocabulary.org/ncl/)
2. Click on close 
3. Got this https://terra-vocabulary.org/ncl/ui/https%3A%2F%2Fterra-vocabulary.org%2Fncl%2F

fyi @sgrellet, @cfollenf

**Comment by der** [comment]
@tendrie Thanks for the report. The solution that @simonoakesepimorphics has put in place allows for better sanitisation of those return URLs while fixing this breakage. Let us know if there is a remaining problem with this.

**Comment by tendrie** [comment]
Thank you @der for your responsiveness, 

We have deployed on our test environment, the issue no longer occurs.  
We  will therefore continue to test, but for now, everything looks fine
