### ISSUE TITLE
Referenced entities' CSV serialisation

### ISSUE THREAD

**Issue by cfollenf** [UKGovLD/registry-core#198]
We are facing systematic errors when client applications query through the API for CSV serialisations of referenced entities.

This happens with requests using the http://registry/{register}?_view=with_metadata&entity={uri}&_format=csv pattern when no register is specified (i.e. the root register is), and neither is a delegation target in the entity's metadata.

Our traces log a single line `SEVERE [http-nio-8080-exec-0] org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo MessageBodyWriter not found for media type=text/csv, type=class org.apache.jena.rdf.model.impl.ModelCom, genericType=class org.apache.jena.rdf.model.impl.ModelCom`

For this example entity https://data.geoscience.fr/ncl/Keywords/_33cfacc4-aace-4e40-a46e-23dd915a5316 the UI correctly redirects download links to its source provider, while the syntactically correct API call https://data.geoscience.fr/ncl/?_view=with_metadata&_format=csv&entity=http%3A%2F%2Fdata.loterre.fr%2Fark%3A%2F67375%2F26L-TRJ2R5X7-G returns an HTTP 500.

While this could be merely ignored, such queries on large registers exclusively containing referenced entities seem to pile up and end up triggering GC overheads, thus crashing the JVM and its running Docker container. Similar queries for RDF serialisations (TTL or JSONLD) do not reproduce the error. Could there be some memory leak when the referenced entity's Jena Model fails to be serialised, or should we focus on defining forwarding rules the API could also follow?

**Comment by der** [comment]
Hi.

It _should_ be clearing up references. Those should just be on the stack and dropped when the thread exits, even though via an exception. However, I don't understand how your external references are working so hard to see how those could make a difference to the behaviour.

In any case it should be possible to handle this better. It shouldn't be getting as far as handing off a ModelCom to be serialised as CSV in the first place. 

The challenge is to recreate the situation. Could you post the full stack trace you are seeing?

But if there's some dump of the store or some cut down example you could supply so we can recreate here that would be much better.

Dave

**Comment by der** [comment]
Never mind, I could recreate the effect and it looks like a pretty straightforward bug to fix.

**Comment by der** [comment]
Hi @cfollenf 

We've implemented a fix for those CSV serialisation errors and build a snapshot at:
 s3://ukgovld/snapshot/com/github/ukgovld/registry-core/2.3.20-SNAPSHOT/registry-core-2.3.20-20241119.094348-1.war

Would you be able to test the snapshot on your data before we crank the handle on a full release process?

Note that as part of this we have disabled conneg to application/json (the registry supports specifically json-ld) and incorrect conneg was causing errors for other users.  Let us know if this causes you problems and we'll look at other ways to avoid the application/json issues.

Dave

**Comment by cfollenf** [comment]
Thank you so much for your reactivity. We're currently going through our internal staging release process and will let you know how it deals with our contents as soon as we've managed to deploy it.

**Comment by cfollenf** [comment]
We're satisfied with our tests on referenced entities data retrieval, and client applications requests already handle the json/json-ld difference, so you as far as we're concerned you may go ahead with your release process.
Thanks again,

**Comment by der** [comment]
We've done a new release (thanks @simonoakesepimorphics ) so [2.3.20](https://github.com/UKGovLD/registry-core/wiki/Release-2.3.20) should fix this issue.

Please let us know if this works.

**Comment by der** [comment]
Assuming this is now working and closing the issue but if that's wrong please re-open or start a new issue.
