### ISSUE TITLE
Editing register description fails

### ISSUE THREAD

**Issue by der** [UKGovLD/registry-core#22]
Using "edit metadata" to modify a register description does not change the displayed description. The difference between the entity description and the metadata (item description) seems to be at the heart of the problem. Compound by the lack of a general edit function for registers.

**Comment by dr-shorthair** [comment]
Confirm this is frustrating us too. Need to be able to edit non-intrinsic information after creation. Annotations qualify.

**Comment by der** [comment]
Enabled "Edit" for registers to allow edit of the register-as-entity non-member-properties
