### ISSUE TITLE
Superseded items must know what they are superseded by

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#38]
When an item status is changed to 'superseded', the UI dialogue must walk through a step to record what it is superseded by. 

Using the API, an request to change status to 'superseded' should fail unless a value for dct:isReplacedBy is provided.

**Comment by dr-shorthair** [comment]
Further discussions with potential adopters have reinforced this requirement. 
1. a successor property is required - 
   reg:successor owl:inverseOf reg:predecessor . 
2. the API should not allow status to be changed to 'superseded' without a reg:successor value being provided.

**Comment by der** [comment]
Done. Added reg:predecessor. Added second argument to the status update API to state the successor, required in the case of setting status to superseded. Normal update also checks that successor is present in metadata before accepting change of status to superseded. Extended UI to provide form field to specify successor and to display successor as part of core metadata.

**Comment by dr-shorthair** [comment]
Onya Dave. Will test soon!
