### ISSUE TITLE
Batch upload - contents only

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#40]
Batch upload is currently supported for container+contents. 
Would be good to allow for contents-only. 

(I just had an initial upload fail because of an error in the source file, but not before the register had already been created. Now I want to load just the contents, but can't do that in a batch. Grrr.)

**Comment by der** [comment]
We now support content-only batch upload (and content only batch edit). Plus all changes should now be properly wrapped in a transaction so a failure will now cleanly abort the entire batch.

**Comment by dr-shorthair** [comment]
You've just negated hours of SPARQL development! (Good stuff.)
