### ISSUE TITLE
Restore backups - links to user database

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#44]
Following up consequences of https://github.com/UKGovLD/registry-core/issues/4 

The transition from OpenID to the local user database is incomplete. 
Since the user database is local, we need to understand the relationship with the registry content to ensure that links are either maintained or can be rebuilt when registry content is restored. 

Say a RegisterItem has  

        reg:submitter      [ foaf:name    "Simon Cox" ;
                             foaf:openid  <simon.cox@csiro.au>
                           ] ;

this interprets the username simon.cox@csiro.au as a URI that identifies the user (of course the @ is not significant - I just happened to use my email address as the username). 
In the UI, when the 'All registration metadata' panel is displayed, the hyperlink interprets this as a relative URI, so for example on 
http://registry.it.csiro.au:49170/agriculture/def/NLMP-glossary/_Adaptation:2
the submitter openid link is expanded to 
      <http://registry.it.csiro.au:49170/agriculture/def/NLMP-glossary/simon.cox@csiro.au> 
This is clearly an error - user ids are not relative to specific register paths, and of course this URI does not resolve. But neither does  <http://registry.it.csiro.au:49170/simon.cox@csiro.au>

1. is there a correct URI form for the users? 
2. does any registry functionality actually depend on the link integrity from RegisterItems to users? Or is this just a 'passive' record, so if the link is broken we don't really need to worry.

**Comment by der** [comment]
Clearly a UI bug but there's no dependency on that link. As you say it's a passive record. In fact others have requested the link be removed anyway, even in cases where the link is meaningful.

**Comment by dr-shorthair** [comment]
1. is there a correct URI form for users?

**Comment by der** [comment]
No. The point of the original design was that the user ID should be externally provided and would be a URI. With the demise of OpenID the design hasn't caught up, it functions but user identity is just an installation specific ID string, not a URI.

**Comment by der** [comment]
The main submitter display is no longer a link. Internally the reg:submitter/foaf:accountName will now use a plain string instead of treating the user ID as a URI.

It could be a future enhancement to have a per-registry URI for users and provide some navigation based on that. However, given the negative feedback about having links for users that would probably have to be a separate fork.
