### ISSUE TITLE
Promote item to register

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#48]
As part of a system evolution, it is sometimes desirable to promote an existing item resource to being a register with its own member items.

**Comment by der** [comment]
This could/should be done by (real) delete then publish a register in its place.

Replacing an item by a register would be a change in semantics and at the moment the notion is that once published the semantics of an item should be stable, new semantics requires a new URI.

**Comment by dr-shorthair** [comment]
Understood.
