### ISSUE TITLE
Requesting version of a top-level registry throws exception

### ISSUE THREAD

**Issue by 6a6d74** [UKGovLD/registry-core#5]
Requesting a version of most registers works fine; e.g.
   
    http://environment.data.gov.uk/registry/structure/org:1 

But requesting a version of a top-level register throws an exception; e.g.

    http://environment.data.gov.uk/registry/structure:1

Exception: 

    HTTP Status 500 - org.apache.velocity.exception.MethodInvocationException: Invocation of method 'perform' in class com.epimorphics.registry.core.Registry threw exception java.lang.IllegalArgumentException at page-deref.vm[line 24, column 34]

**Comment by der** [comment]
Fixed
