### ISSUE TITLE
UI: TreeView: paging in list vire mode flips back to tree view mode.

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#61]
When viewing a register organised as hierachical concept scheme the page initially opens in a tree view. Clicking on the control at the top of the list gives the first page of a list view . 

However, clicking in the next page link at the bottom of the pages switches back to the tree view rather than stepping to the next page. 

I suspect that this is a problem is that the links on page stepping controls are missing a `listView=true` parameter.

**Comment by der** [comment]
Fixed in registry-config-base and -env2 and -loc2
