### ISSUE TITLE
UI for paging search results broken

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#64]
It appears that paging of search results is not working. 

http://registry.it.csiro.au/ui/text-search?query=law 
http://registry.it.csiro.au/ui/text-search?query=science 
each generate a report that spills over more than one page. 
While the API call 

http://registry.it.csiro.au/ui/text-search?query=science&page=N 

does generate the right response, the link on the page in the UI has dropped the 'query=word' part of the argument.

**Comment by der** [comment]
Thanks, fixed.
