### ISSUE TITLE
Paging: final link to empty page unexpected

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#69]
Paging through results of a search, if the final page has reached the end of the list, it is confusing to see a link to an empty 'next page'. For example, there is a [>>] at the bottom of 
     http://registry.it.csiro.au/ui/text-search?page=1&query=science 
but the next page has no additional results. 

Mind you, I don't know why entities like 
   http://registry.it.csiro.au/def/keyword/nature/subjects/computer-science 
are not showing up in the result set ...

**Comment by dr-shorthair** [comment]
Looks like the problem might be elsewhere - none of my search sets are paging past 2. 
Any suggestions what we should look for?

**Comment by der** [comment]
This has been covered off list but recording this here as well.

In this case the search has exactly 25 results (the default page size). It is not until you try to fetch the next page and get an empty list that the UI knows you have reached the end. The only way to address this without API changes would be to force a second query for next page to validate whether a follow page really exists, which would double the already troubling page delay. Given a uniform distribution of page sizes then 96% of the time that doubling would serve no purpose. I think the occasional blank follow-on page is a reasonable compromise.

The non-matching entities are being returned not as matches but as spurious data in the entity description graphs. Why there is such spurious data is a separate question :)

**Comment by dr-shorthair** [comment]
Fair enough.
