### ISSUE TITLE
Registry appears to use different version of LDP ontology

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#7]
Registers in the registry have properties
   ldp:membershipPredicate
   ldp:inverseMembershipPredicate
The LDP Ontology published at http://www.w3.org/ns/ldp has 
   ldp:hasMemberRelation
   ldp:isMemberOfRelation 
instead.

**Comment by der** [comment]
I've added support for the ldp:hasMemberRelation and ldp:isMemberOfRelation in addition to the prior ldp:membershipPredicate and reg:inverseMembershipPredicate.

This should make it possible for new applications to use the new versions of LDP without breaking existing usage.
