### ISSUE TITLE
Relative URI has "/" appended

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#70]
POSTing an entity whose description includes a link to the register using a relative URI. 
The URI is processed to add a "/" after. 
Here's the test case: 
Create a register with 

```
@prefix dct: <http://purl.org/dc/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ui:      <http://purl.org/linked-data/registry-ui#> .
@prefix reg:     <http://purl.org/linked-data/registry#> .

<test1>
    a skos:ConceptScheme , reg:Register ;
    dct:description "A register for testing #1"@en ;
    rdfs:label "Test 1"@en ;
    ui:hierarchyRootProperty	skos:topConceptOf ;
    ui:hierarchyChildProperty	skos:narrower .
```

Then load the content into that register with 

```
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .
@prefix dct:   <http://purl.org/dc/terms/> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .

<entity1>
        a                 skos:Concept ;
        rdfs:label        "test entity 1"@en ;
        dct:description   "A test entity #1"@en ;
        skos:narrower      <entity2> ;
        skos:topConceptOf     <> .
        
<entity2>
        a                 skos:Concept ;
        rdfs:label        "test entity 2"@en ;
        dct:description   "A test entity #2"@en ;
        skos:broader      <entity1> .
```

**Comment by der** [comment]
The data seems to have got mangled, use code quotes to protect it from markdown.

The data doesn't seem to include a definition of <> as a ConceptScheme so that will be by passing the BulkTypes machinery. Is that intentional?

**Comment by dr-shorthair** [comment]
Sorry - I've quoted the code now. 

In order to save having to be accurate with the rdfs:member tag, I usually use a two-step process to create and load a register. Hence two ttl docs. The first is POSTed to create the register. Then the second is POSTed to that register. All done with relative URIs so I can test in one place then load permanently somewhere else without having to tinker with the data.

**Comment by der** [comment]
Thanks. I don't think it is possible to change that without creating a magic special case.

The issue, of course, is what to treat as the baseURI when resolving the relative URIs in the payload.

If we are POSTing to a register `http://myregistry/def/test1` then we treat `http://myregistry/def/test1` as the URI for the register and `http://myregistry/def/test1/`as the parent resource for the children and thus as the base URI for the resolution.

This means that the relative URI `<entity1>` is then resolved to `http://myregistry/def/test1/entity1` as we would expect.

It naturally also means that `<>` resolves to `http://myregistry/def/test1/` which is strictly not the register.

If regarded the base URI as being `http://myregistry/def/test1` then `<>` would resolve as you are asking for but  `<entity1>` would then resolved to `http://myregistry/def/entity1` which is definitely not helpful.

This is consistent with how bulk registration types are treated. In that case we would typically have:

    <test1>   a skos:ConceptScheme , reg:Register ; ... .
    <test1/entity1> a skos:Concept; ... .

Note the presence of the `/` between the register relative URI and the entity relative URI.

I don't think you can refer to the parent register URI without knowing it's relative name. Thus:

```
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .
@prefix dct:   <http://purl.org/dc/terms/> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .

<entity1>
        a                 skos:Concept ;
        rdfs:label        "test entity 1"@en ;
        dct:description   "A test entity #1"@en ;
        skos:narrower      <entity2> ;
        skos:topConceptOf     <../test1> .
```

That still allows your payloads to be independent of the location to which they are posted but does mean that the child payloads are specific to the relative name of the parent register. Which doesn't seem unreasonable given you are trying to refer to it.

**Comment by dr-shorthair** [comment]
Yep - <../test1> is the workaround I have been using. 
Am just trying to strip my processes back to the minimal set that supports an optimal test-submit sequence.
