### ISSUE TITLE
Error in OAuth configuration instructions

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#74]
In https://github.com/UKGovLD/registry-core/wiki/Configuration#oauth-configuration it says 

"... append /registry/system/security/responseoa to the base URI ..."

I think it should be 

"... append /system/security/responseoa to the base URI ..."

**Comment by der** [comment]
Agreed, fixed, thanks.

[It arose because several of our instances have a root which is `{domain}/registry`, so for them you append `/registry/system/security/responseoa` to the domain but the `/registry` segment is indeed part of the base URI.
