### ISSUE TITLE
Misplaced VALUEs in LibReg.LABEL_QUERY

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#87]
The label fetching query in LibReg injects the URI for resources of interest into a SPARQL query via a VALUES statement which is misplaced in the query template - such that the query is slow on a large registers and fails to return the expected labels (haven't quite figured out why not). Moving the values statement inside each branch of the UNION vastly improves the performance (71ms from >4s) and effectiveness (returns labels) of the query.

Pull request with  fix to follow.

**Comment by der** [comment]
Thanks for the fix.
