### ISSUE TITLE
Real delete operation failing

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#89]
Running a local dev copy of the jersey 2 branch head revision, and logged in as an Admin, the real delete operation via the UI fails, responding with a "400 Bad Request" with a plain text message saying `Did not recognize request`.

This occurs running in a Windows 7 x64 environment with an Oracle 8 64 bit JVM. 

This occurs using current versions of both Firefox and Chrome.

The problem seems to be at line 419 of `RequestProcesser` which tests `form==null`. `form` is coming through as non-null, but empty (i.e. `form.size()==0`). Because `form` is non-null execution skips around the code block that test for the presence of `?real_delete` - and hence the request fails as an unrecognised operation.

Pull request to follow offering *a* fix - that simply extends the test to include empty, non-null form values. But there may be other subtluties to in the disinction between null and non-null but empty values of `form`

**Comment by der** [comment]
Thanks for the patch.

**Comment by der** [comment]
Actually, it turns out this patch was for an obsolete branch that should have been removed. The delete function does work on the active branch. Thanks anyway.
