### ISSUE TITLE
RealDelete removing adjacent `reg:entity` references for entities registered in multiple registers.

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#91]
This may be related to issue #82

For one of our projects we have multiple registers that register the same entity, but each represents a different hierarchical arrangement of the *same* set of concepts.

While (real)deleting one register (during development of the data prep for these registers) it became apparent that the operation deletes the `reg:entity` references from the `reg:definition` associated with registrations (RegisterItems) for the *other* registers in which the entity is registered.

I think I have tracked the problem down to the following code in StoreBaseImpl:

```
    private Collection<Resource> scanAllVersions(Resource root, StreamRDF stream, Collection<Resource> sofar) {
        addRefClosure(stream, root);
        for (Resource version : getDefaultModel().listSubjectsWithProperty(DCTerms.isVersionOf, root).toList()) {
            addRefClosure(stream, version);
            addRefClosure(stream, getResourceValue(version, Version.interval));
            Resource definition = getResourceValue(version, RegistryVocab.definition);
            if (definition != null) {
                Resource graph = getResourceValue(definition, RegistryVocab.sourceGraph);
                if (graph != null) {
                    sofar.add(graph);
                }
                Resource entity = getResourceValue(definition, RegistryVocab.entity);
                if (entity != null) {
                    scanAllVersions(entity, stream, sofar);
                }
            }
            Resource graph = getResourceValue(version, RegistryVocab.annotation);
            if (graph != null) {
                sofar.add(graph);
            }
        }
        return sofar;
    }
```

In particular line 952:
`scanAllVersions(entity, stream, sofar);`

which by the action of the `addRefClosure` calls, now on `entity` values, schedules deletion of all references in the store's default graph *to* the entity in question which will include the references from adjacent registers. It also schedules deletion of the BNodeClosure rooted at the entity (again scoped by the store's default graph (afaict).

I think the problems are two-fold. Firstly a need to scope the `reg:entity` deletions to the register item version being deleted. Secondly, the deletion of the BNodeClosure rooted at the entity may need to be deferred until after the last `reg:entity` reference to the entity has been deleted (or at least been scheduled for deletion).

I'll try to prepare a couple of small register definitions that could be used to expore this problem and a SPARQL query that can be used to find cases where it has happened.

**Comment by skwlilac** [comment]
`scanAllVersions` is also used in the `CommandExport` operation, and in the case of multiple registrations (in different registers) of the same entity, there a 'floating' `[ reg:entity <someentity> ]` detached from any associated RegisterItem which correspond to registrations in *other* registers - which corelates well with the over deletion of `reg:entity` triples report above.

**Comment by skwlilac** [comment]
Attached is a zip'ed up collection of bulk upload register and content files intended to establish a situation where there 4 registers with that share registrations of common entities.

- `/registry/test/id`        the main register intended to contain the main registration of the common entities (1-5)
- `/registry/test/a-reg`  registers a subset (1-3) of the common entities  - as an *internal* external reference.
- `/registry/test/b-reg`  registers similarly registers a different subset (2-4) of the common entities.
- `/registry/test/c-reg`  registers similarly registers a different subset (3-5) of the common entities.

To set this up:

1. take a clean registry-core installation (run with a context path of '/registry');
2. stop the registry and delete `/opt/ldregistry/store`
3. Unpack the attached [issue-91-test-registers.zip](https://github.com/UKGovLD/registry-core/files/1047521/issue-91-test-registers.zip) file in `/var/opt/ldregistry/boot` (which should include the enclosed test registers in the registry boot up process).
4. Start the registry.
5. Check that the registry contains the 4 registers  listed above with entity content as described.

## Single item deletion

Login as an Admin, navigate to 'C Register'.  Use the Actions UI to delete "Entity 5" shared only with the `id` register.

Now visit `/register/test/id`. "Entity 5" is now missing form the 'ID Register'

Using the following SPARQL query at the SPARQL form reveals that the `reg:entity` statement has been deleted from the corresponding register item version's `reg:definition`:

```
prefix reg: <http://purl.org/linked-data/registry#>

describe ?itemVer ?thing
where {
  ?itemVer reg:definition ?definition .
  
  ?thing ?p ?itemVer .
  FILTER NOT EXISTS { ?definition reg:entity [] }
}
```

At this point it is not possible to restore the 'ID Register' by simply reloading its content by repeating the step above. Although `Entity 5` is now 'missing' from that register, the bulk upload now reports:

```
Action failed: Bad Request -

reg-id-content.ttl - Item already registered at request location: http://environment.data.gov.uk/registry/test/id/_5
```

which correspond the damaged register item.

Revisiting 'C Register' and deleting `Entity 3` shared with ALL the other test registers, removes that entity from all the test register and leaves similarly damaged register item versions for the corresponding entity in 'ID Register', 'A-Register' and 'B-Register'. The SPARQL query above again reveals the situation in the store.

[issue-91-test-registers.zip](https://github.com/UKGovLD/registry-core/files/1047521/issue-91-test-registers.zip)

**Comment by der** [comment]
Believed fixed. A simplified version of test case is included in main test suite and now passes
