### ISSUE TITLE
`LibReg.addLabels` doesn't retrieve labels for properties. 

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#92]
When displaying entities within a register, if some of the properties used in describing the entity are themselves contained within the registry, it is preferable to display the property's label rather than some presentation of it's local name.

The frontend `_item-render.vm` call `$lib.reg.addLabels($entity)` in order to make labels for the entity and its property values, however the current implementation of `LibReg.addLabels` does not include any available labels for the properties themselves.

A pull request with a suggested fix to follow.

**Comment by der** [comment]
Now implemented in java8 branch
