### ISSUE TITLE
maven build problem

### ISSUE THREAD

**Issue by eroux** [UKGovLD/registry-core#94]
Hello,

I'm quite interested in your platform, I tried to build it by cloning it then `mvn clean package`, but I'm getting:

```
[ERROR] Failed to execute goal on project registry-core: Could not resolve dependencies for project com.github.ukgovld:registry-core:war:2.0.0-SNAPSHOT: Failed to collect dependencies at com.epimorphics:appbase:jar:2.1.1-SNAPSHOT: Failed to read artifact descriptor for com.epimorphics:appbase:jar:2.1.1-SNAPSHOT: Could not transfer artifact com.epimorphics:appbase:pom:2.1.1-SNAPSHOT from/to ukgovld-s3-snapshot (s3://ukgovld/snapshot): Unable to load AWS credentials from any provider in the chain
```

Do I need credentials to download the snapshot versions?

Thank you!

**Comment by der** [comment]
Hi,
The 2.0.0-SNAPSHOT is under development right now so using one of the released wars might be more stable :)

That said it ought to be buildable without credentials. I've just uploaded a fresh SNAPSHOT release of the dependency it is complaining about, can you try again?

Dave

**Comment by eroux** [comment]
I still have the same problem, but I installed the snapshot version from github by hand (and noticed that there was no license, I opened an issue) and it fixed the problem... thanks!
