### ISSUE TITLE
CSV upload fails when cell values include single quote characters.

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#96]
The simple treatment of table cell values in `RDFCSVUtil.toTurtle(String value)` fails to escape single quote characters when they occur within an uploaded CSV file.

Attached is a file set up to be loaded into a "product-categories" register that fails to load due to single quote characters in the label fields of several entries.

[food-product-truncated.zip](https://github.com/UKGovLD/registry-core/files/1249236/food-product-truncated.zip)

**Comment by der** [comment]
That's because the encode half does the escaping of single quotes, which is why round tripping is safe.

Agreed that not having to use \ escaping for single quotes would be easier for hand authored CSVs.

**Comment by der** [comment]
Various fixes to multi-value splitting, changed policy so that a lone ' is now allowed in source (and had to change writer to match).
